# -*- coding: utf-8 -*-
"""work_NS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATj9DwANVaNDhJPU4ThnHS_coQqI76ra
"""

# импортируем библиотеки
import keras
from keras.layers import Dense
import numpy as np
import matplotlib.pyplot as plt

classification_data = [
    [1, 1, 1, 1],
    [1, 1, 0, 1],
    [1, 0, 1, 0],
    [1, 0, 0, 0],
    [0, 1, 1, 1],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [1, 1, 0, 1],
    [1, 0, 1, 0],
    [0, 1, 1, 1],
    [0, 0, 0, 0]
]
X_cls = np.array(classification_data)[:, :3]
y_cls = np.array(classification_data)[:, 3]

model = keras.Sequential()
model.add(Dense(3, activation="tanh", input_dim=3))
model.add(Dense(5, activation="tanh"))
model.add(Dense(1, activation="sigmoid"))

print(model.summary())

model.compile(loss="binary_crossentropy", metrics=['accuracy'], optimizer='adam')

history = model.fit(X_cls, y_cls, batch_size=16, epochs=50)

no_criminal_record = int(input())
sane = int(input())
education = int(input())
prediction = model.predict(np.array([[no_criminal_record, sane, education]]))
e = np.round(prediction)
print(e)

plt.plot(history.history['loss'])
plt.grid(True)
plt.show()

print(model.evaluate)

model.save('work_NS.keras')